name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Say Node version
        run: echo "Running with Node version ${{ inputs.node-version }}"
